#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]
    args.domain = "auth.domain.tld"
    args.path = "/"
    args.portal_subdomain = "auth"
    args.default_policy = "open"
    args.session_duration = "24h"
    args.upstream_scheme = "https"
    args.upstream_host = "127.0.0.1"
    args.upstream_port = "443"
    args.first_username = "mfaadmin"
    args.first_display_name = "MFA Admin"
    args.first_email = "mfaadmin@example.test"
    args.first_password = "YnhStrongPassw0rd!"

    exclude = ["install.private", "install.multi", "install.subdir", "change_url"]

    [default.curl_tests]
    home.path = "/"
    home.expect_return_code = 302
    home.auto_test_assets = false
