#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMON="$ROOT_DIR/package-base/scripts/_common.sh"
CONFIG_SCRIPT="$ROOT_DIR/package-base/scripts/config"
INSTALL_SCRIPT="$ROOT_DIR/package-base/scripts/install"
UPGRADE_SCRIPT="$ROOT_DIR/package-base/scripts/upgrade"
REMOVE_SCRIPT="$ROOT_DIR/package-base/scripts/remove"

grep -q '^_mfa_sidecar_sync_protected_domain_includes() {' "$COMMON"
grep -q '^_mfa_sidecar_remove_protected_domain_includes() {' "$COMMON"
grep -q 'reinject-all' "$COMMON"
grep -q '_mfa_sidecar_install_reinject_hooks' "$COMMON"
grep -q '_mfa_sidecar_remove_reinject_hooks' "$COMMON"
grep -q '_mfa_sidecar_write_sudoers' "$COMMON"
grep -q '_mfa_sidecar_remove_sudoers' "$COMMON"
grep -q '_mfa_sidecar_sync_protected_domain_includes' "$CONFIG_SCRIPT"
grep -q '_mfa_sidecar_remove_protected_domain_includes' "$CONFIG_SCRIPT"
grep -q '_mfa_sidecar_sync_protected_domain_includes' "$INSTALL_SCRIPT"
grep -q '_mfa_sidecar_install_reinject_hooks' "$INSTALL_SCRIPT"
grep -q '_mfa_sidecar_write_sudoers' "$INSTALL_SCRIPT"
grep -q '_mfa_sidecar_sync_protected_domain_includes' "$UPGRADE_SCRIPT"
grep -q '_mfa_sidecar_install_reinject_hooks' "$UPGRADE_SCRIPT"
grep -q '_mfa_sidecar_write_sudoers' "$UPGRADE_SCRIPT"
grep -q '_mfa_sidecar_remove_protected_domain_includes' "$REMOVE_SCRIPT"
grep -q '_mfa_sidecar_remove_reinject_hooks' "$REMOVE_SCRIPT"
grep -q '_mfa_sidecar_remove_sudoers' "$REMOVE_SCRIPT"
test -f "$ROOT_DIR/package-base/sources/hooks/post_app_upgrade-reinject"
test -f "$ROOT_DIR/package-base/sources/hooks/conf_regen-reinject"
test -f "$ROOT_DIR/package-base/sources/hooks/apply-runtime-as-root"

echo "smoke_include_sync_contract: ok"
